// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package game

import "math/rand"

const choiceRandomPanicMsg = "Impossible to get item from empty slice"

func choiceRandomColor(list []Color) Color {
	listLength := len(list)

	if listLength == 0 {
		panic(choiceRandomPanicMsg)
	}

	index := rand.Intn(listLength)
	return list[index]

}
