// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package shape

import "math/rand"

func choiceRandomShape(list []Shape) Shape {
	listLength := len(list)

	if listLength == 0 {
		panic("Impossible to get item from empty slice")
	}

	index := rand.Intn(listLength)
	return list[index]

}
