// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package shape

import (
	"reflect"
	"testing"
)

func TestChoiceRandomShape(t *testing.T) {
	list := make([]Shape, 1)
	result := choiceRandomShape(list)

	if !reflect.DeepEqual(result, list[0]) {
		t.Fatalf("!reflect.DeepEqual(%#v, %#v)", result, list[0])
	}
}

func TestChoiceRandomShapePanic(t *testing.T) {
	defer func() {
		err := recover()

		if !reflect.DeepEqual(err, choiceRandomPanicMsg) {
			t.Errorf("Invalid panic: expect \"%v\", got \"%v\"", choiceRandomPanicMsg, err)
		}
	}()

	choiceRandomShape(make([]Shape, 0))
}
